[package]
name = "react-example-app-1"
version = "0.1.0"
authors = ["Irisawa Masaru <irisawa.masaru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cli-cmd"
path = "cli-bin/src/main.rs"

[dependencies]
